-- MySQL Script generated by MySQL Workbench
-- 02/04/17 21:35:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projeto_hailton_php
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto_hailton_php
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto_hailton_php` DEFAULT CHARACTER SET utf8 ;
USE `projeto_hailton_php` ;

-- -----------------------------------------------------
-- Table `projeto_hailton_php`.`SIST_MODULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_hailton_php`.`SIST_MODULO` (
  `SIMO_PK` INT NOT NULL AUTO_INCREMENT,
  `SIMO_DESCRICAO` VARCHAR(45) NULL,
  PRIMARY KEY (`SIMO_PK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_hailton_php`.`SIST_ACESSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_hailton_php`.`SIST_ACESSO` (
  `SIAC_PK` INT NOT NULL AUTO_INCREMENT,
  `PESS_PK` INT NULL,
  PRIMARY KEY (`SIAC_PK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_hailton_php`.`CDTR_FUNCAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_hailton_php`.`CDTR_FUNCAO` (
  `CAFU_PK` INT NOT NULL AUTO_INCREMENT,
  `CAFU_DESCRICAO` VARCHAR(45) NULL,
  PRIMARY KEY (`CAFU_PK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_hailton_php`.`CDTR_PESSOA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_hailton_php`.`CDTR_PESSOA` (
  `PESS_PK` INT NOT NULL AUTO_INCREMENT,
  `CAFU_PK` INT NULL,
  `CALO_PK` INT NULL,
  `CURS_PK` INT NULL,
  `PESS_NOME` VARCHAR(45) NULL,
  `PESS_FOTO` BLOB NULL,
  `PESS_LATTES` VARCHAR(200) NULL,
  `PESS_DT_NASCIMENTO` DATE NULL,
  PRIMARY KEY (`PESS_PK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_hailton_php`.`CDTR_LOGIN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_hailton_php`.`CDTR_LOGIN` (
  `CALO_PK` INT NOT NULL AUTO_INCREMENT,
  `CALO_LOGIN` VARCHAR(15) NULL,
  `CALO_SENHA` VARCHAR(10) NULL,
  PRIMARY KEY (`CALO_PK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_hailton_php`.`SIST_AUDITORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_hailton_php`.`SIST_AUDITORIA` (
  `AUDI_PK` INT NOT NULL AUTO_INCREMENT,
  `AUDI_DESCRICAO` BLOB NULL,
  `AUDI_TABELA_PK` INT NULL,
  PRIMARY KEY (`AUDI_PK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_hailton_php`.`QEST_QUESTIONARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_hailton_php`.`QEST_QUESTIONARIO` (
  `QEST_PK` INT NOT NULL AUTO_INCREMENT,
  `QEST_DESCRICAO` VARCHAR(100) NULL,
  PRIMARY KEY (`QEST_PK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_hailton_php`.`QEST_QUESTOES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_hailton_php`.`QEST_QUESTOES` (
  `QETO_PK` INT NOT NULL AUTO_INCREMENT,
  `QEST_PK` INT NULL,
  `TIQE_PK` INT NULL,
  `QETO_DESCRICAO` VARCHAR(200) NULL,
  PRIMARY KEY (`QETO_PK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_hailton_php`.`QEST_RESPOSTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_hailton_php`.`QEST_RESPOSTAS` (
  `RESP_PK` INT NOT NULL AUTO_INCREMENT,
  `QETO_PK` INT NULL,
  `RESP_DESCRICAO` VARCHAR(200) NULL,
  PRIMARY KEY (`RESP_PK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_hailton_php`.`QEST_TIPO_QUESTAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_hailton_php`.`QEST_TIPO_QUESTAO` (
  `TIQE_PK` INT NOT NULL AUTO_INCREMENT,
  `TIQE_DESCRICAO` VARCHAR(50) NULL,
  PRIMARY KEY (`TIQE_PK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_hailton_php`.`CDTR_CURSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_hailton_php`.`CDTR_CURSO` (
  `CURS_PK` INT NOT NULL AUTO_INCREMENT,
  `CURSO_DESCRICAO` VARCHAR(100) NULL,
  PRIMARY KEY (`CURS_PK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_hailton_php`.`CDTR_ALUNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_hailton_php`.`CDTR_ALUNO` (
  `ALUN_PK` INT NOT NULL AUTO_INCREMENT,
  `PESS_PK` INT NULL,
  PRIMARY KEY (`ALUN_PK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_hailton_php`.`SIST_VERSAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_hailton_php`.`SIST_VERSAO` (
  `VERS_PK` INT NOT NULL,
  `VERS_DT` DATE NULL,
  PRIMARY KEY (`VERS_PK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_hailton_php`.`QEST_QUESTIONARIO_APLICACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_hailton_php`.`QEST_QUESTIONARIO_APLICACAO` (
  `QEAP_PK` INT NOT NULL AUTO_INCREMENT,
  `QEST_PK` INT NULL,
  `COLA_PK` INT NULL,
  `CURS_PK` INT NULL,
  `QEAP_DT_APLICACAO` DATE NULL,
  `QEAP_PERIODO` VARCHAR(50) NULL,
  PRIMARY KEY (`QEAP_PK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_hailton_php`.`CDTR_COLABORADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_hailton_php`.`CDTR_COLABORADOR` (
  `COLA_PK` INT NOT NULL AUTO_INCREMENT,
  `PESS_PK` INT NULL,
  PRIMARY KEY (`COLA_PK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_hailton_php`.`QEST_APLICACAO_ALUNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_hailton_php`.`QEST_APLICACAO_ALUNO` (
  `APAL_PK` INT NOT NULL AUTO_INCREMENT,
  `QEAP_PK` INT NULL,
  `ALUN_PK` INT NULL,
  PRIMARY KEY (`APAL_PK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_hailton_php`.`QEST_ALUNO_RESPOSTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_hailton_php`.`QEST_ALUNO_RESPOSTA` (
  `ALRE_PK` INT NOT NULL AUTO_INCREMENT,
  `RESP_PK` INT NULL,
  `ALUN_PK` INT NULL,
  PRIMARY KEY (`ALRE_PK`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
